<a href="https://colab.research.google.com/github/hedgehog-zowie/tf-study/blob/master/numpy_study.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
# 构造一个多维数组
a1 = np.array([[1,2,3],[4,5,6]])
# 显示维度及每维数组大小
a1.shape

(2, 3)

In [0]:
# 构造一个多维数组的多维数组
a2 = np.array([[[111,112,113,114],[121,122,123,124]], [[211,212,213,214],[221,222,223,224]], [[311,312,313,314],[321,322,323,324]]])

In [0]:
a2.shape

(3, 2, 4)

In [0]:
# 显示维数
a2.ndim

3

In [0]:
# 显示元素总数
a2.size

18

In [0]:
# 显示元素类型
a2.dtype

dtype('int64')

In [0]:
# 显示每个元素的字节数
a2.itemsize

8

In [0]:
# 创建一个0-26的3 X 3 X 3的数组
a3=np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [0]:
# 创建3 X 4的全0数组
a4 = np.zeros((3,4))
a4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [0]:
# 创建2 X 3 X 4的全1数组
a5 = np.ones((2,3,4))
a5

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [0]:
# 创建一个范围在[10, 30)区间内，间隔为5的数组
a6 = np.arange( 10, 30, 5 )
a6

array([10, 15, 20, 25])

In [0]:

# 创建一个在[0, 2]区间内个数为9的数组
a7 = np.linspace( 0, 2, 9)
a7

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [0]:
# 点乘与矩阵乘法， 点乘用*， 矩阵乘法用dot函数
b1 = np.array([[1,2], [3,4]])
b2 = np.array([[0,1], [1,0]])

In [0]:
b1 * b2

array([[0, 2],
       [3, 0]])

In [0]:
b1.dot(b2)

array([[2, 1],
       [4, 3]])

In [0]:
# asix参数的用法
b = np.arange(12).reshape(3,4)
print(b)
# axis=0(第0维) 将针对每一个列进行运算，如 b.sum(axis=0) 将矩阵 b 中每一个列的所有元素都相加为一个标量
r=b.sum(axis=0)
print('sum of each column: ', r)
# axis=1(第1维) 将针对每一行进行运算，如b.min(axis=1)将矩阵b中每一行的最小元素
r=b.min(axis=1) 
print('min of each row:', r)
# r=b.max(axis=2) 由于只有2维，因此axis=2会报错——“axis 2 is out of bounds for array of dimension 2”

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
sum of each column:  [12 15 18 21]
min of each row: [0 4 8]


In [0]:
# 数组操作
a = np.arange(10)**3
print(a)
# 下标从0开始，如a[2]取第3个元素
print(a[2])
# 取下标区间[2,5)的元素
print(a[2:5])
# 取下标区间[0,6)的元素，且对能被3整除的下标元素进行操作，如下，将第0,3两个个元素设置为-1000
a[:6:3] = -1000
print(a)
# 反转数组，没有指定维度时，空缺的维度被默认为取所有元素。
r=a[ : : -1]
print(r)

[  0   1   8  27  64 125 216 343 512 729]
8
[ 8 27 64]
[-1000     1     8 -1000    64   125   216   343   512   729]
[  729   512   343   216   125    64 -1000     8     1 -1000]


In [0]:
# 数组堆叠
x = 10*np.random.random((2,2))
print(x)
# floor 向下取整
a = np.floor(x) 
print('a=', a)
# ceil 向上取整
b = np.ceil(x) 
print('b=', b)
# vstack 垂直堆叠
r=np.vstack((a, b))
print('vstack=', r)
# hstack 水平堆叠
r=np.hstack((a, b))
print('hstack=', r)
# column_stack 堆叠一维数组为2维数组的列
a = np.array([4.,2.])
b = np.array([3.,8.])
r=np.column_stack((a, b))
print('column_stack=', r)
# row_stack 
r=np.row_stack((a, b))
print('row_stack=', r)

[[7.52017613 5.73675115]
 [8.12505733 5.67751328]]
a= [[7. 5.]
 [8. 5.]]
b= [[8. 6.]
 [9. 6.]]
vstack= [[7. 5.]
 [8. 5.]
 [8. 6.]
 [9. 6.]]
hstack= [[7. 5. 8. 6.]
 [8. 5. 9. 6.]]
column_stack= [[4. 3.]
 [2. 8.]]
row_stack= [[4. 2.]
 [3. 8.]]


In [0]:
# python参数是引用传递，因此数据复制不要直接用=号赋值
a = np.arange(12)
b = a
print('b is a: ', b is a)
# view函数可以使两个对象共享元素，但可改变形状
c = a.view()
print('c is a: ', c is a)
print('c.base is a: ', c.base is a)
c.shape = 2,6
print('a.shape: ', a.shape)
print('c.shape: ', c.shape)
a[0] = 1000
print('a = ', a)
print('c = ', c)
# copy函数是深拷贝，数据不共享
d = a.copy()
print('d is a: ', d is a)
print('d.base is a: ', d.base is a)
a[0]=9999
d[0]=8888
print('a = ', a)
print('d = ', d)

b is a:  True
c is a:  False
c.base is a:  True
a.shape:  (12,)
c.shape:  (2, 6)
a =  [1000    1    2    3    4    5    6    7    8    9   10   11]
c =  [[1000    1    2    3    4    5]
 [   6    7    8    9   10   11]]
d is a:  False
d.base is a:  False
a =  [9999    1    2    3    4    5    6    7    8    9   10   11]
d =  [8888    1    2    3    4    5    6    7    8    9   10   11]
